### ISSUE TITLE
Add OTA handlers as McAfee Embedded Control updaters

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/meta-device-cloud#22] opened 2018-03-02 10:50 UTC
Once installed into an IDP system, the device manager OTA handler will not be able to perform an update if MEC/solidcores is enabled.

For example:
McAfee Solidifier[5089]: McAfee Solidifier prevented unauthorized execution of '/var/lib/python-device-cloud/otapackage/install.sh' by process /bin/bash (Process Id: 5632, User: dc)

Can we add the OTA handlers (standard and offline) as McAfee updaters in solidcore.conf ?

**Comment by element-82** [comment] 2018-03-15 15:54
I think this issue is not a bug, more an IDP config issue.  Closing.

**Closed by element-82** 2018-03-15 15:54 UTC
